# Generated by Django 5.0.6 on 2024-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GoldSilverAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], max_length=6)),
                ('karate', models.CharField(choices=[('24K', '24K'), ('22K', '22K'), ('21K', '21K'), ('18K', '18K'), ('Traditional', 'Traditional')], max_length=11)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('Gram', 'Gram'), ('Vori', 'Vori')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
