# Generated by Django 5.0.6 on 2024-06-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaat_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldsilverasset',
            name='karate',
        ),
        migrations.AddField(
            model_name='goldsilverasset',
            name='karat',
            field=models.CharField(choices=[('', 'Karat...'), ('1', '24K'), ('2', '22K'), ('3', '21K'), ('4', '18K'), ('5', 'Traditional')], default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='goldsilverasset',
            name='category',
            field=models.CharField(choices=[('', 'Category...'), ('1', 'Gold'), ('2', 'Silver')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='goldsilverasset',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldsilverasset',
            name='unit',
            field=models.CharField(choices=[('', 'Unit...'), ('1', 'Gram'), ('2', 'Vori')], default='', max_length=4),
        ),
    ]
