# Generated by Django 5.0.6 on 2024-06-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaat_calculator', '0002_remove_goldsilverasset_karate_goldsilverasset_karat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessasset',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidmoney',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
