# Generated by Django 5.0.6 on 2024-06-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakaat_calculator', '0003_alter_businessasset_amount_alter_debt_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessAsset',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='GoldSilverAsset',
        ),
        migrations.DeleteModel(
            name='LiquidMoney',
        ),
    ]
